ARG GOLANG_VERSION

FROM golang:${GOLANG_VERSION}

ARG GODEB_VERSION
ENV GODEB_VERSION ${GODEB_VERSION:-0}

# TODO: exit build if wget fails
RUN set -ex;
RUN wget --show-progress -O /usr/local/bin/dep \
      https://github.com/golang/dep/releases/download/v${GODEB_VERSION}/dep-linux-amd64; \
    chmod +x /usr/local/bin/dep;